remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # Add this line to the plugins list if you already have one
title: Vibe Store  # 
description: cloths, computer accessories  # 
theme: minima  # Set your theme (change to whatever theme you use)
url: "https://VibeStoreHub.github.io"  # Base URL for your site
author: 
  name: "PK"  # Add your name or business
  email: "your-email@example.com"  # Optional: Add contact info
social:
  github: "https://github.com/username"  # Add links to your social profiles
  twitter: "https://twitter.com/username"
  linkedin: "https://linkedin.com/in/username"
plugins:
  - jekyll-sitemap
  - jekyll-feed
